{% set name = "qtoml" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qtoml-{{ version }}.tar.gz
  sha256: 7f2d0c2c39659d2a408ae93d02a068e0d22eb67e16e474239f7735ff1094b1ba

build:
  entry_points:
    - qtoml_testdecode = qtoml.__main__:decode
    - qtoml_testencode = qtoml.__main__:encode
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry >=0.12
    - pip
  run:
    - python >={{ python_min }},<4.0.0
    - attrs >=19.3.0,<22.0
    - click >=7.0,<9.0

    # Listed under dev but needed for cli
    - python-dateutil >=2.7,<3.0

test:
  imports:
    - qtoml
  commands:
    - pip check
    - qtoml_testdecode --help
    - qtoml_testencode --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/alethiophile/qtoml
  summary: TOML encoder/decoder stabler than uiri/toml and faster than PyTOML
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
